# =========================
# GitHub Actions CI/CD Workflow
# This workflow:
# 1. Triggers on push or pull request to main branch
# 2. Runs on a self-hosted runner (local machine)
# 3. Builds Docker image
# 4. Pushes Docker image to Docker Hub
# 5. Deploys container locally on self-hosted server
# =========================

name: CI/CD Pipeline  # Workflow name shown in GitHub Actions tab

# -------------------------
# Trigger configuration
# -------------------------
on:
  push:                # Trigger when code is pushed
    branches: ['main'] # Only for main branch
  pull_request:        # Trigger when PR is opened/updated
    branches: ['main'] # Only for main branch

jobs:
  build-test-push-deploy:
    runs-on: self-hosted   # Run this on your own machine, not GitHub's cloud runners

    steps:
      # -------------------------
      # 1. Checkout the repo code
      # -------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3

      # -------------------------
      # 2. Log in to Docker Hub
      # -------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}     # Stored in GitHub Secrets

      # -------------------------
      # 3. Build and push Docker image
      # -------------------------
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .   # Current directory
          push: true   # Push image to Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-docker:latest

      # -------------------------
      # 4. Deploy container locally
      # -------------------------
      - name: Deploy on self-hosted server
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-docker:latest
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 5009:5009 --name flask-app ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-docker:latest
