name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test-push-deploy: 
    runs-on: self-hosted

    # sDOCKER_IMAGE: RAHUL70007/flask-ci-cd
      # version: 
    steps: 

      - name: Checkout Repository
        uses: actions/checkout@v3

    # log in to docker hub
      - name : Login to Docker Hub
        uses: docker/login-action@v2

      - name: Log in to Docker Hub  
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{}}